In [245]:
import pandas as pd
import numpy as np

In [246]:
df = pd.read_csv('homeprices.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [247]:
dummies = pd.get_dummies(df.town)
dummies = dummies * 1
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [248]:
merged = pd.concat([df,dummies],axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [249]:
final = merged.drop(['town','robinsville'], axis=1)
final

area   price  monroe township  west windsor
0   2600  550000                1             0
1   3000  565000                1             0
2   3200  610000                1             0
3   3600  680000                1             0
4   4000  725000                1             0
5   2600  585000                0             1
6   2800  615000                0             1
7   3300  650000                0             1
8   3600  710000                0             1
9   2600  575000                0             0
10  2900  600000                0             0
11  3100  620000                0             0
12  3600  695000                0             0

In [250]:
x = final.drop(['price'], axis=1)
x

area  monroe township  west windsor
0   2600                1             0
1   3000                1             0
2   3200                1             0
3   3600                1             0
4   4000                1             0
5   2600                0             1
6   2800                0             1
7   3300                0             1
8   3600                0             1
9   2600                0             0
10  2900                0             0
11  3100                0             0
12  3600                0             0

In [251]:
y = final.price

In [252]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [253]:
model.fit(x,y)

LinearRegression()

In [254]:
model.predict(x)

array([539709.73984091, 590468.71640508, 615848.20468716, 666607.18125133,
       717366.1578155 , 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [255]:
model.predict([[3500,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([653917.43711029])

In [256]:
model.score(x,y)

0.9573929037221872

In [257]:
model.predict([[2452,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([560942.89400131])

In [258]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [259]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [260]:
x = dfle[['town','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [261]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [262]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder='passthrough')

In [263]:
x = ct.fit_transform(x)


In [264]:
x = x[:,-1:]
x

array([[2600.],
       [3000.],
       [3200.],
       [3600.],
       [4000.],
       [2600.],
       [2800.],
       [3300.],
       [3600.],
       [2600.],
       [2900.],
       [3100.],
       [3600.]])

In [265]:
model.fit(x,y)
model

LinearRegression()

In [266]:
model.predict([[1,1,4512]])

ValueError: X has 3 features, but LinearRegression is expecting 1 features as input.

In [267]:
model.predict([[0,1,5400]])

ValueError: X has 3 features, but LinearRegression is expecting 1 features as input.